// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCIT8b2_WpZixMt-6pzUPVjU__9y3xrG4',
    appId: '1:278780970997:web:4837f4c4c5c1c211ad02bc',
    messagingSenderId: '278780970997',
    projectId: 'bavaria-firebase',
    authDomain: 'bavaria-firebase.firebaseapp.com',
    storageBucket: 'bavaria-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUeC67iXSHfK3t0ING0wjpKXnfw_cUS1o',
    appId: '1:278780970997:android:0903825d0275a9e4ad02bc',
    messagingSenderId: '278780970997',
    projectId: 'bavaria-firebase',
    storageBucket: 'bavaria-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxRHK7fkbmj6JYwkPT25PD-zK3GirOWPk',
    appId: '1:278780970997:ios:7be9a7435362d167ad02bc',
    messagingSenderId: '278780970997',
    projectId: 'bavaria-firebase',
    storageBucket: 'bavaria-firebase.appspot.com',
    iosBundleId: 'com.example.prouductlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxRHK7fkbmj6JYwkPT25PD-zK3GirOWPk',
    appId: '1:278780970997:ios:31a83f14424f5e86ad02bc',
    messagingSenderId: '278780970997',
    projectId: 'bavaria-firebase',
    storageBucket: 'bavaria-firebase.appspot.com',
    iosBundleId: 'com.example.prouductlist.RunnerTests',
  );
}
